services:
  tymek_ovh:
    image: ghcr.io/tymekv/tymek.ovh:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - default
      - proxy
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.port: 3000
      traefik.http.services.tymek_ovh.loadbalancer.server.port: "3000"
      traefik.http.routers.tymek_ovh.rule: "Host(`tymek.ovh`)"

networks:
  default:
  proxy:
    name: proxy-network
    external: true
